#################### Macros #####################

PROJ = CatEyeB.Tests

# CC macros
COMMON_CFLAGS = -static-libgcc
CFLAGS = -O3
CDEFINES =

# CPP macros (additional to C macros)
COMMON_CPPFLAGS = -static-libstdc++
CPPFLAGS = 
CPPDEFINES =

# Universal macros
LIBS = 
CUSTOM_INCLUDES =
#CUSTOM_JARS = $(ECLIPSE_HOME)/plugins/org.junit_4.8.2.v4_8_2_v20110321-1705/junit.jar;$(ECLIPSE_HOME)/plugins/org.hamcrest.core_1.1.0.v20090501071000.jar
#CUSTOM_JARS = ../ExternalLibs/lib/org.junit_4.8.2.v4_8_2_v20110321-1705/junit.jar;../ExternalLibs/lib/org.hamcrest.core_1.1.0.v20090501071000.jar
SOURCE = src
TARGET = ../target
JAVA_JNI_CLASSES = 
NATIVE_LIB = CatEyeB.Core.Native1

include ../target/makefiles/cpp_java_cross.mk